import isaaclab.sim as sim_utils 
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

USD_PATH = "/home/isaac/Documents/Github/IsaacLab-dhkim/scripts/prestoe/newprestoe/prestoeCC2/prestoe_CC2.usd"

PRESTOE_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=USD_PATH,
        activate_contact_sensors=True,
        rigid_props = sim_utils.RigidBodyPropertiesCfg(
            rigid_body_enabled=True,
            #TODO: modify the contraints to ensure that the simulation does not diverge during training
            max_linear_velocity = 1000,
            max_angular_velocity = 1000,
            max_depenetration_velocity = 100,
        ),
        # all articulation props set to default
        articulation_props= sim_utils.ArticulationRootPropertiesCfg(
            articulation_enabled=True,
            enabled_self_collisions=True,
            solver_position_iteration_count=32,
            solver_velocity_iteration_count=1,
            stabilization_threshold=0.001,
        ),
    ),
    actuators={
        "R_AL_pulley_pitch_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["R_AL_pulley_pitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_toe_pulley_pitch_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["R_toe_pulley_pitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_AR_pulley_pitch_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["R_AR_pulley_pitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_AL_pulley_pitch_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["L_AL_pulley_pitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_toe_pulley_pitch_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["L_toe_pulley_pitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_AR_pulley_pitch_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["L_AR_pulley_pitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "torsoyaw_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["torsoyaw"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_hipyaw_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["R_hipyaw"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_hipyaw_acc" : ImplicitActuatorCfg(
            joint_names_expr= ["L_hipyaw"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_hiproll_acc" : ImplicitActuatorCfg(
            joint_names_expr=["R_hiproll"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_hiproll_acc" : ImplicitActuatorCfg(
            joint_names_expr=["L_hiproll"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_hippitch_acc" : ImplicitActuatorCfg(
            joint_names_expr=["R_hippitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_hippitch_acc" : ImplicitActuatorCfg(
            joint_names_expr=["L_hippitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_shoulderpitch_acc" : ImplicitActuatorCfg(
            joint_names_expr=["R_shoulderpitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_shoulderroll_acc" : ImplicitActuatorCfg(
            joint_names_expr=["R_shoulderroll"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_shoulderyaw_acc" : ImplicitActuatorCfg(
            joint_names_expr=["R_shoulderyaw"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "R_elbowpitch_acc" : ImplicitActuatorCfg(
            joint_names_expr=["R_elbowpitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_shoulderpitch_acc" : ImplicitActuatorCfg(
            joint_names_expr=["L_shoulderpitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_shoulderroll_acc" : ImplicitActuatorCfg(
            joint_names_expr=["L_shoulderroll"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_shoulderyaw_acc" : ImplicitActuatorCfg(
            joint_names_expr=["L_shoulderyaw"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
        "L_elbowpitch_acc" : ImplicitActuatorCfg(
            joint_names_expr=["L_elbowpitch"],
            stiffness=0,
            damping=0,
            friction=300,
            effort_limit=400.0,
            velocity_limit=100.0,
        ),
    }
)