# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L32
seed: 42

n_timesteps: !!float 1e8
policy: 'MlpPolicy'
n_steps: 64 
batch_size: 192
gae_lambda: 0.95
gamma: 0.99
n_epochs: 8 
ent_coef: 0.000001
vf_coef: 0.001
learning_rate: !!float 3e-4
clip_range: 0.2
policy_kwargs: "dict(
                  activation_fn=nn.ELU,
                  net_arch=[32, 32]
                )"
target_kl: 0.01
max_grad_norm: 1.0
device: "cuda:0"
